version: "3.8"

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: senha123
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: ./app
    depends_on:
      - db
    ports:
      - "80:5000"
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=senha123

volumes:
  db_data: