name: Deploy to VM Azure via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          mkdir -p ~/app

          if [ ! -d ~/app/.git ]; then
            git clone https://github.com/gaformario/dataops-github-actions.git ~/app
          fi

          cd ~/app

          git pull

          if [ ! -f Dockerfile ]; then
            echo "Dockerfile não encontrado!"
            exit 1
          fi

          docker build -t flask-api .
          docker stop flask-api || true
          docker rm flask-api || true
          docker run -d -p 80:80 --name flask-api flask-api